### ISSUE TITLE
Add localization

### ISSUE THREAD

**Issue by westnordost** [sargunv/maplibre-compose#135]
Add localization for strings used in "ornament" composables.

This could probably be populated from the MapLibre Android/iOS/JS SDK. For basic stuff like "OK", maybe there is already something available in Compose?

**Comment by sargunv** [comment]
Hmm, I'm worried [this error](https://stackoverflow.com/questions/57906510/adding-a-library-with-more-translations-than-the-app-has-gives-errors-in-string) might get annoying downstream if we support any languages that the callers don't support.

We could document adding `resConfigs` to the build file, but I think it's simplest just to expose the strings as parameters for callers to translate as they see fit?

**Comment by westnordost** [comment]
I disabled this lint check via
```
    lint {
        disable += listOf(
            "MissingTranslation", // crowd-contributed translations are incomplete all the time
        )
    }
```
in my app

**Comment by sargunv** [comment]
The remaining non localized strings used in the Material ornaments are the accessibility content descriptions on the two buttons.
