### ISSUE TITLE
design better api for adding images to the style

### ISSUE THREAD

**Issue by sargunv** [sargunv/maplibre-compose#169]
#168 got image loading functionality on iOS and Android, but it's pretty rough right now

* images are added to the map in a different place from where they're referenced
* the ids are strings and must match
* I'm pretty sure it doesn't efficiently handle adding/removing images

this should be cleaned up before release

also probably relevant: `StyleState` and `StyleManager` have closely related purposes. Should they be one thing?

**Comment by sargunv** [comment]
cc @westnordost for api thoughts

**Comment by westnordost** [comment]
Of course, 
```
iconImage = painterResource(Res.drawable.marker),
```
would be most convenient. But don't know if this would work already when taking into account that one may want to reference an image from the style and that the whole thing could be an expression, too.

**Comment by westnordost** [comment]
Layers are part of the style too, yet they don't need to be referred from the `rememberStyleState`. So, maybe the solution for Images could be like for Layers. As nodes in the composition.

**Comment by sargunv** [comment]
> As nodes in the composition.

It's possible, but I'd like to avoid that. I used to have sources as nodes in the composition, and found it really weird in implementation and somewhat weird in API to have elements not part of the actual layout (so, layers) be nodes in the composition tree. Basically had to make the code placing layers skip over any non-layer node in a big list containing all the nodes.

Now, sources are passed as a reference to a layer node. They insert/remove themselves to/from the style with a DisposableEffect (so those remember source functions can only be called inside the map composition). But I plan to refactor this to insert/remove them at layer insertion/removal so you can create/remember a source wherever you want; there wouldn't be an implicit dependency on being called inside the map composition. The style manager would need to reference count the sources to determine when it's time to insert/remove a source.

It'd be nice to do the same for images, but there's 5(?) different places expressions containing images can get passed into a style, so all five of those would need to hook into the image reference counting mechanism.

Of course, we also need to support referring to images from the base style. Sources have a `getBaseSource(id)` function. I see two potential approaches here:

First, mirror the sources api; have a `rememberImage(painterResource(Res.drawable.example))` and a `getBaseImage("example")`, then pass the value returned from that into the `image` function of the expression DSL:

```kt
MapLibreMap(..) {
  val marker = rememberImage(painterResource(Res.drawable.marker))
  val poi = getBaseImage("poi-icon")
  SymbolLayer(
    ..
    iconImage = image(marker)
  )
  SymbolLayer(
    ..
    iconImage = image(poi)
  )
}
```

but rather than mirroring sources explicitly, I feel it's better to just have overloads to `image`:

```kt
MapLibreMap(..) {
  SymbolLayer(
    ..
    iconImage = image(Res.drawable.marker)
  )
  SymbolLayer(
    ..
    iconImage = image("poi-icon")
  )
}
```

Perhaps some token object representing `Res.drawable.marker` can be inserted into the expression. Then, the layer composable calls some helper that scans the expression, registers any new images found in it, and replaces those tokens with strings for the image id

**Comment by sargunv** [comment]
I've updated it so the expression system accepts an `ImageBitmap` so you can do this if your images are bitmaps:

```kt
val marker = imageResource(Res.drawable.marker)

MaplibreMap(..) {
  SymbolLayer(
    ..
    iconImage = image(marker)
  )
}
```

Vector images are more complex; you have to draw them to a bitmap first. The demo app does this:

```kt
val marker = painterResource(Res.drawable.marker).rememberAsBitmap()
MaplibreMap(..) {
  SymbolLayer(
    ..
    iconImage = image(marker)
  )
}
```

```kt
@Composable
private fun Painter.rememberAsBitmap(): ImageBitmap {
  val density = LocalDensity.current
  val layoutDirection = LocalLayoutDirection.current
  return remember(this, density, layoutDirection) {
    ImageBitmap(intrinsicSize.width.toInt(), intrinsicSize.height.toInt()).also { bitmap ->
      CanvasDrawScope().draw(density, layoutDirection, Canvas(bitmap), intrinsicSize) { draw(size) }
    }
  }
}
```

It might be convenient to provide that converter as a `public` util, but it feels out of scope for the library. At the very least we should include it in docs/examples if we don't provide it as a util.

**Comment by sargunv** [comment]
oh, and `format` now works with `image`:

```kt
SymbolLayer(
  ..
  textField =
    format(
      span(image(const("railway"))),
      span(const(" ")),
      span(get(const("STNCODE")).asString(), fontScale = const(1.2f)),
    ),
)
```

**Comment by westnordost** [comment]
It would be really nice if the user could also pass a Painter and MapLibre-Compose would take care of creating the bitmap and caching it itself.

Anyway, my use case for adding images to the map is this:

I display OpenStreetMap POIs on the map and use the iD editor presets for that. There are currently about 700 icons for different POIs, including, of course, icons for quite rare things. So, I only want to load and rasterize those pictures that I actually need. So, I have this class

[`MapImages`](https://github.com/streetcomplete/StreetComplete/blob/993018694df25ca2241f7abfbb7fc8210599f870/app/src/main/java/de/westnordost/streetcomplete/screens/main/map/maplibre/MapImages.kt)

which manages creating the bitmap and adding an icon **once** (adding an image with the same name twice produces an error, IIRC) to the style, so it can be used by a symbol layer.

Then, when displaying new data, [I call this class ](https://github.com/streetcomplete/StreetComplete/blob/993018694df25ca2241f7abfbb7fc8210599f870/app/src/main/java/de/westnordost/streetcomplete/screens/main/map/components/StyleableOverlayMapComponent.kt#L222) to ensure that the pictures I need are added.

I wonder if this is possible with the new API you devised? Didn't look at it yet, because, well, Merry Christmas! 😀 🎄

**Comment by sargunv** [comment]
With the new API, as long as you pass the same ImageBitmap instance, the image will be reused. Internally, I keep a cache of ImageBitmap to generated id.

Can do the same with a Painter too (after sleeping on it, I've realized it makes sense for that to be another `image` overload and participate in the same cache).

**Comment by sargunv** [comment]
Now the image expression accepts `Painter`, and will draw it to a bitmap once and reuse the bitmap if that same Painter instance is referenced multiple times:

```kt
val marker = painterResource(Res.drawable.marker)

MaplibreMap(..) {
  SymbolLayer(
    ..
    iconImage = image(marker)
  )
}
```
