### ISSUE TITLE
Support Compose Web (browser)

### ISSUE THREAD

**Issue by sargunv** [sargunv/maplibre-compose#25]
We should ideally support Compose Web, so JS and/or WASM targets.

Problems to solve:
* JS, WASM, or both?
* Generate or write Kotlin bindings for [MapLibre GL JS](https://maplibre.org/maplibre-gl-js/docs/)
* Interop with Compose UI. Currently the web target doesn't have anything like AndroidView / SwingPanel / UIKitView to interop with a non-compose UI element. https://github.com/ShreyashKore/wonderous_compose seemingly works around it with absolute positioning of a map canvas on top of the compose UI.
  * This'll work for many cases, but not when the user wants to display Compose UI elements over the map.
  * Desktop's SwingPanel also has this limitation, see #24 (though I believe there's an experimental flag to make it integrate more like iOS UIKitView)
  * HTML Canvases are transparent by default. Both Compose UI and MapLibre render to (their own) canvases. Is there potential for some more advanced compositing with some kind of mask?
* Spatial-K doesn't currently have JS/WASM target, though it's pure Kotlin so easy to add. I have a PR open for WASM support [here](https://github.com/dellisd/spatial-k/pull/142), but if the library is unmaintained we'll need to fork it

**Comment by josxha** [comment]
Hi @sargunv, awesome work you're doing. I'm on a similar journey with [flutter-maplibre](https://github.com/josxha/flutter-maplibre). I'll try to list all of the differences between maplibre native (android specifically) and maplibre-gl-js. No guarantee for completeness, though. I hope this is any help to you (:

1. **Attribution**: Android has a Icon button that when clicked shows a dialog with the list of registered attributions. web shows an overlay with text that is initially expanded but collapses when the map moves.
2. **Compass**: Native has a compass that is enabled by default and indicates the map rotation. Web has a "rotate north" button that indicates the current rotation and if enabled the camera pitch. 
3. **Zoom buttons**: Web has optional zoom buttons, Native has not.
4. **Scalebar**: Web has a scalebar, Native has not
5. **Location button**: Web has an optional "show location" button, native does not have this.
6. **Location marker**: Native has a dot or pointer to indicate bearing. Web has only a very simple location indicator that does not support displaying the bearing and can only be activated when the user clicks on the "location" button https://github.com/maplibre/maplibre-gl-js/issues/2688
7. **3D Terrain**: web supports 3D hillshade, native does not https://github.com/maplibre/maplibre-native/issues/252
8. **3D Models**: web supports GLTF models, native does not, https://github.com/maplibre/maplibre-native/issues/2806
9. **Animated camera movement**: Native uses e.g. `animateCamera()` that takes the animation duration as parameter. Web has its `flyTo` function that supports an animation speed but no fix animation duration.
10. **Pitch vs Tilt** I've seen mixed namings of pitch and tilt on Android. Web seems to use tilt concistently.
11. **PMTiles** Native has an open pull request for pmtiles, web has not discussed adding support for it. https://github.com/maplibre/maplibre-native/pull/2882
12. **MBTiles** Native supports mbtiles, web does not.
13. **Caching & Offline**: As far as I've seen there is no good way to handle the cache on web. Native has full control and offline functionality.
14. **Permissions**: Android has the `PermissionManager`, Web does not have a similar concept. The permission gets requested automatically when needed.
15. **Max camera pitch**: Android has a max camera pitch, while web supports up to 85.
16. **Globe**: (soon) web has soon support for a globe view, native has not.
17. **Query Features at position**: Web and Android have different implementations of `queryRenderedFeatures`, https://github.com/maplibre/maplibre-native/issues/2828
18. **Simple Marker**: Web has a simple Marker, Android has its annotation plugin, https://maplibre.org/maplibre-gl-js/docs/examples/add-a-marker/

**Comment by sargunv** [comment]
This is tremendously helpful, thank you!

**Comment by sargunv** [comment]
`main` now has basic web support
