### ISSUE TITLE
Support adding image to style

### ISSUE THREAD

**Issue by michalgwo** [sargunv/maplibre-compose#37]
Adding images to style can be useful when we want to add a Symbol with a custom icon, which is not available in the style sprites. A common use case is adding a marker.

Functions from MapLibre Native:
- Android: [addImage ](https://maplibre.org/maplibre-native/android/api/-map-libre%20-native%20-android/org.maplibre.android.maps/-style/add-image.html)or [addImageAsync](https://maplibre.org/maplibre-native/android/api/-map-libre%20-native%20-android/org.maplibre.android.maps/-style/add-image-async.html)
- iOS [setImage:forName:](https://maplibre.org/maplibre-native/ios/latest/documentation/maplibre/mlnstyle/setimage:forname:)

**Comment by sargunv** [comment]
perhaps the API for this can work similarly to Sources

**Comment by sargunv** [comment]
looked into this, the only somewhat complex bit is converting a Compose ImageBitmap into a UIImage (and even that doesn't seem too tough). I think this'll be the first thing I do for v0.4.0

**Comment by sargunv** [comment]
it works. api is still rough; need to think about exactly how it should be designed. #169 will track that.

Demo app has a new demo now of loading a vector drawable and displaying it with a SymbolLayer:

![Screenshot_20241223_170934_maplibre-compose-demo.jpg](https://github.com/user-attachments/assets/92e3f522-c29f-4c1d-a30d-158d8ca80fec)

![IMG_0005](https://github.com/user-attachments/assets/01f37fbc-f92c-4d0a-b36c-4380628bf546)
