### ISSUE TITLE
Explore reimplementing ornaments in Compose / Material3 in a separate module, using camera state

### ISSUE THREAD

**Issue by sargunv** [sargunv/maplibre-compose#40]
see discussion in: https://github.com/sargunv/maplibre-compose/issues/13

ideally in a separate module so users can opt-in to it (built in ornaments will still be supported)

compass should:
* use material3 style
* have all the same behavior as the native compass
* also reset pitch on tap by default (like google maps compass), configurable

eventually scale bar, attribution, etc too, requirements tbd

**Comment by westnordost** [comment]
For my app, I already have a widget for the compass, it's here:

https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/screens/main/controls/CompassButton.kt

https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/screens/main/controls/MapButton.kt

As you see, it's not exactly a lot of code, hehe, but anyways, I hereby release the two linked files under the terms of the BSD-3-Clause license, maybe it can be helpful `¯\_(ツ)_/¯`

**Comment by sargunv** [comment]
scale bar tbd but #153 creates the new module; it'll be included in the next release
