### ISSUE TITLE
[DRAFT] v0.2.0 Changelog

### ISSUE THREAD

**Issue by sargunv** [sargunv/maplibre-compose#68]
Milestone: https://github.com/sargunv/maplibre-compose/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen+milestone%3Av0.2.0

Contributors:
* @sargunv 
* @westnordost 
* @michalgwo 

Breaking changes from v0.1.0:
* Require click handlers to consume or pass the event, optionally preventing later handlers from receiving it
* Overhaul layer property expressions to:
  * Replace Strings with Enums in many fields, wherever appropriate
  * Narrow `Expression<Number>` to only accept `Float` literals
  * Change `Expression<Number>` to `Expression<Dp>` where appropriate
  * Replace `Expression<Point>` with `Expression<DpOffset>` or `Expression<Offset>`
  * Replace `Expression<Insets>` with `Expression<PaddingValues.Absolute>`
  * Most functions for working with expressions have overloads for the new types, but in some edge cases you may need to use `.dp` and `.value` to convert between `Expression<Dp>` and `Expression<Number>`.
* Relocate some types. For example, `.core.data` and `.core.camera` are now directly under the parent `.core`.

Other API changes:
* CameraState additions:
  * query rendered features at point/rect with filters
  * convert between screen space and world space coordinates
  * get the world space visible bounding box and region polygon
  * get the reason the camera is moving (user gesture vs programmatic)
* Add click handlers on the `MaplibreMap` composable
* Optimize default values of layer property expressions to avoid allocating new `Expression` objects when layers recompose
* Add support for setting the target frame rate of the map renderer, and a callback to listen for the actual frame rate
* Integrate the Kermit logger passed to the `MaplibreMap` composable with the iOS/Android SDK's logging configuration
  * This doesn't yet apply to MapLibre Native Android's HTTP logger
* Make MapLibre Native Android an `api` dependency so consumers can configure static stuff (like the HTTP logger)
* Reduce Android minSDK to 23 from 24
* Explicitly enable strong skipping in the compose compiler

Documentation changes
* Create new documentation website with mkdocs for installation, feature overview, etc
  * and relocate the pre-existing Dokka reference site to /api/ under the main docs site
* Upgrade API reference docs with links to external docs and to source code
* Add some missing API reference documentation

**Comment by westnordost** [comment]
> Require click handlers to consume or pass the event, optionally preventing later handlers from receiving it

Why not return true/false?

**Comment by sargunv** [comment]
It's unclear to me when reading the code what true/false indicates (true as in, yes pass the event to other handlers or true as in, yes consume the event). Solvable with docs but I tend to prefer self documenting names/types over docs where possible (just like the expression units)
